### PR TITLE
D3v4 fix

### PR DESCRIPTION
**Pull request by pavloDeshko**
fix for https://github.com/tibotiber/rfd-update-example/issues/1

### CODE REVIEW

**Comment by tibotiber** [comment]
@pavloDeshko Thanks a lot for this and sorry for the crazy late reply. Good catch on forgetting to merge the enter and update sets. One thing though, because you moved the transition to after setting `cx` and `cy`, the update set jumps instead of translating. I'd suggest to set `cx` and `cy` for the enter set and then update them all, what do you think?

```js
    // remove unneeded circles
    circle.exit().remove()

    // create any new circles needed
    const newCircles = circle
      .enter()
      .append('circle')
      .attr('cy', yBuffer)
      .attr('cx', function (d, i) {
        var spacing = lineLength / data.length
        return xBuffer + i * spacing
      })
      .attr('r', 0)

    // update all circles to new positions
    newCircles
      .merge(circle)
      .transition()
      .duration(500)
      .attr('cy', yBuffer)
      .attr('cx', function (d, i) {
        var spacing = lineLength / data.length
        return xBuffer + i * spacing
      })
      .attr('r', function (d, i) {
        return d
      })
```

**Comment by pavloDeshko** [comment]
Sure this will do the job
Although there's no need to reassign cy attribute for all circles, 
and I'd wrap cx logic for DRY

   ```
const getCx = function (d, i) {
        var spacing = lineLength / data.length
        return xBuffer + i * spacing
      }
   // create any new circles needed
    const newCircles = circle
      .enter()
      .append('circle')
      .attr('cy', yBuffer)
      .attr('cx', getCx)
      .attr('r', 0)

    // update all circles to new positions
    newCircles
      .merge(circle)
      .transition()
      .duration(500)
      .attr('cx',getCx)
      .attr('r', function (d, i) {
        return d
      })
```

**Comment by tibotiber** [comment]
Good points @pavloDeshko. Can you update the PR?

**Comment by pavloDeshko** [comment]
done 
will you update your sandbox?

**Comment by tibotiber** [comment]
@pavloDeshko thanks a lot for your work. I have updated the link to the sandbox that's synced to the repo.

**Pull request merged**
